### ISSUE TITLE
Crash when shift right clicking with IC2 wrench or Yeta wrench

### ISSUE THREAD

**Issue by agow100** [DoughnutServers/DonutCraftATL#61]
Whenever I shift right click with an IC2 wrench or a Yeta wrench I crash with this crash log: http://pastebin.com/phseKFd6

**Comment by agow100** [comment]
I tested it on the official donutcraft server and it crashes there too. So I know it's not just on my own server.

**Comment by DoughnutDev** [comment]
Are you right clicking a RFTool Block?

On Nov 27, 2016 12:11 PM, "agow100" <notifications@github.com> wrote:

I tested it on the official donutcraft server and it crashes there too. So
I know it's not just on my own server.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DoughnutServers/DonutCraftATL/issues/61#issuecomment-263134089>,
or mute the thread

**Comment by agow100** [comment]
I am not right clicking an RFTool block. It happens with any block.
